# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0003_remove_chapter_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
