# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0004_auto_20160924_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
