# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0005_auto_20160924_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('volume', 'n_chap')]),
        ),
        migrations.AlterUniqueTogether(
            name='manga',
            unique_together=set([('name', 'author')]),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('manga', 'n_vol')]),
        ),
    ]
