# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0006_auto_20161003_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-name']},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('volume', 'n_chap', 'title', 'script')]),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('manga', 'n_vol', 'title')]),
        ),
    ]
