# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0007_auto_20161011_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['name']},
        ),
    ]
