# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0008_auto_20161011_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['n_chap']},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['n_vol']},
        ),
    ]
