# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0012_auto_20161017_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set([('manga', 'n_vol')]),
        ),
    ]
