# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0013_auto_20161017_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
