# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0014_manga_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volume',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
