# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0016_auto_20161018_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='translated',
            field=models.BooleanField(default=False),
        ),
    ]
