# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0017_chapter_translated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='manga',
            name='user',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='volume',
            name='user',
            field=models.IntegerField(default=7),
        ),
    ]
