# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0018_auto_20161024_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volume',
            name='user',
            field=models.IntegerField(),
        ),
    ]
