# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 14:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0020_auto_20161024_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='n_chap',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='volume',
            name='n_vol',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
