# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangascripts', '0022_auto_20161024_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter_read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangascripts.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chapter_read',
            unique_together=set([('chapter', 'user')]),
        ),
    ]
