# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0023_auto_20161025_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter_read',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='chapter_read',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapter_read',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chapter_read',
        ),
    ]
