# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0027_auto_20161027_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mangascripts.Manga'),
            preserve_default=False,
        ),
    ]
