# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0028_chapter_manga'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set([('manga', 'n_chap')]),
        ),
    ]
