# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangascripts', '0031_auto_20161028_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_user',
            name='favourite_manga',
        ),
        migrations.RemoveField(
            model_name='app_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='App_User',
        ),
    ]
